### ISSUE TITLE
Move mesa-geo examples into mesa-examples repo

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa-geo#128]
Move mesa-geo examples int mesa-examples repo - https://github.com/projectmesa/mesa-examples 
We should have more discussion on folders or no at this time before we make this move. 

Relevant comments to folder structure:  https://github.com/projectmesa/mesa/issues/963#issuecomment-1326932082 and subsequent comments

**Comment by jackiekazil** [comment]
@wang-boyu do you want to take this on? I am more than willing to do this, but I look to you to determine when I good time might be. Let me know.

**Comment by wang-boyu** [comment]
Sure I can work on this. There are some minor changes to the examples in an open PR that needs some more work: https://github.com/projectmesa/mesa-geo/pull/127. I'll move the examples after it is merged.

In addition there's one more example: https://github.com/wang-boyu/agents-and-networks-in-python which wasn't here because of some extra dependencies. I'll move that as well.

**Comment by jackiekazil** [comment]
Sounds like a plan!

**Comment by wang-boyu** [comment]
Update: examples have been merged into mesa-examples repo: https://github.com/projectmesa/mesa-examples/pull/17

I'll leave this issue open until I figure out a way to update the examples page in mesa-geo docs: https://mesa-geo.readthedocs.io/en/latest/examples/overview.html. Basically the docs use the README files inside the examples folder - so the current examples folder can't be simply removed.

**Comment by jackiekazil** [comment]
@tpike3 can we get this on the schedule for discussion for May ... this feel like something we should address in the main repo too.

**Comment by wang-boyu** [comment]
Examples have been moved to mesa-examples repo. Closing the issue now.
