### ISSUE TITLE
Agent collisions

### ISSUE THREAD

**Issue by eecoo** [projectmesa/mesa-geo#53]
**What's the problem this feature will solve?**

Solves the problem that two agents are in the exact same coordinates, in the real world two poeple cant be in the exact same spot

**Comment by wang-boyu** [comment]
This would be a useful feature for certain cases, and involve a physics engine in order to do collision detection. Looks like similar functionalities have been added into MASON (a Java ABM library) as an extension:
- https://docplayer.net/22323269-Building-a-2d-physics-engine-for-mason-christian-thompson-gmu-cs-798.html
- https://cs.gmu.edu/~eclab/projects/mason/extensions/physics2d/PhysicsEnginePresentation.pdf
- source code: https://github.com/eclab/mason/tree/master/contrib/physics2d

For us, there should be several 2d physics engines available in Python. I'm wondering whether it makes more sense to have it as a separate Mesa extension, like the case for MASON.

**Comment by rht** [comment]
> For us, there should be several 2d physics engines available in Python.

Yeah, there should be some that already exist.

**Comment by wang-boyu** [comment]
As a workaround, we can randomly assign agents' location to avoid them standing on top of each other. These are demonstrated in some example models in this repo:

**raster data model**
In the [Population model](https://github.com/projectmesa/mesa-geo/tree/main/examples/population), to assign random positions to people within the same raster cell: https://github.com/projectmesa/mesa-geo/blob/e6be96d69ff96574cb16b6694bcbf0d1f5c390b8/examples/population/population/model.py#L22-L32

**vector data model**
In the [GeoSchelling (Points & Polygons) model](https://github.com/projectmesa/mesa-geo/tree/main/examples/geo_schelling_points), to assign random positions to people within the same polygon: https://github.com/projectmesa/mesa-geo/blob/e6be96d69ff96574cb16b6694bcbf0d1f5c390b8/examples/geo_schelling_points/geo_schelling_points/space.py#L27-L32

As mentioned above, physics engines won't be implemented within mesa-geo for now. Hence I'm closing this issue as won't fix. But pls feel free to continue the discussion here. We can also convert this to a discussion if needed.
